src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 */
//fait la relation entre class et les tables en bdd
class Person
{
    /**
     * @var int
     * 
     * @ORM\Id
     * @ORM\GeneratedValue //autoincrément
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @var string
     * @ORM\Column() //définit que cet attribut doit etre un champ dans la table > par défaut le champ est un varchar(255) NOT NULL
     */
    private $firstname;
    /**
     * @var string
     * @ORM\Column()
     */
    private $lastname;
    /**
     * @var string
     * @ORM\Column(unique=true) //précise que ce champ doit etre unique
     */
    private $email;
    /**
     * @var \Datetime
     * @ORM\Column(type="date") //précise que ce champ et de type date
     */
    private $birthdate;
    
    
    public function getId() {
        return $this->id;
    }

    public function getFirstname() {
        return $this->firstname;
    }

    public function getLastname() {
        return $this->lastname;
    }

    public function getEmail() {
        return $this->email;
    }

    public function getBirthdate(): \Datetime {
        return $this->birthdate;
    }

    public function setFirstname($firstname) {
        $this->firstname = $firstname;
        return $this; //permet de chainer les appels de methodes grace à la case à cocher 'fluent'
    }

    public function setLastname($lastname) {
        $this->lastname = $lastname;
        return $this;
    }

    public function setEmail($email) {
        $this->email = $email;
        return $this;
    }

    public function setBirthdate(\Datetime $birthdate) {
        $this->birthdate = $birthdate;
        return $this;
    }


    public function getFullname() {
        return $this->firstname . ' '. $this->lastname;
    }

}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use function dump;

/**
 * @Route("/person") //définit toutes les routes avec la base /persone/autrerep
 */
class PersonController extends Controller
{
    /**
     * @Route("/list") // donne la chemin complet /person/list // si je met dans un @ Route("/") se sera le chemin par défaut si je tape juste dans l'url /person
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        //em pour entity manager 
        //nous renvoie l'entity manger qui est la class qui permet d'interagir avec la bdd
        
        $personRepository = $em->getRepository(Person::class); //toutes les class on un attribut static qui s'appel class -> il revoit le nom complet de la class en chaine de caractère donc :App\Entity\Person
                        //il récupère le repository de la class person
        
        //le repository permet d'interagir avec la bdd pour la table en question
        $persons = $personRepository->findAll(); //ici select * from person
        dump($persons);
        return $this->render('person/index.html.twig', [
           'persons' => $persons
        ]);
    }
    
     /**
     * @Route("/{id}", requirements={"id":"\d+"}) //l'id doit etre un nombre (\d+ en expression régulière qui veut dire un ou plusieurs chiffres)
     * @param int $id
     */
    public function detail($id)
    {
        
         $em = $this->getDoctrine()->getManager();
        $personRepository = $em->getRepository(Person::class);
        
        //find() renvoi l'objet person ou null sur la requete select * from person were id = x
        $person = $personRepository->find($id); //find uniquement sur un id
        dump($person);
        if(is_null($person)){
            throw new NotFoundHttpException;
        }
         return $this->render('person/detail.html.twig', [
           'person' => $person
        ]);
    }
    
    /**
     * @Route("/search")
     */
    public function searchByLastname(Request $request)
    {
        $person=null;
        $persons=null;
        
        if($request->isMethod('POST')){
            $em = $this->getDoctrine()->getManager();
            $personRepository = $em->getRepository(Person::class);
            $person = $personRepository->findOneBy(['email'=>$request->request->get('email')]); // récupère l'info email du post et l'envoie dans la requete
                    //findOnBy retourn 0 ou 1 résultatsinon erreur 
            $persons = $personRepository->findBy(['lastname'=>$request->request->get('lastname')]);
        }
       return $this->render('person/search.html.twig', [
          'person' => $person,
          'persons' => $persons,
        ]);
    }
}

templates/person/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{person.fullname}}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
   
    <h1>Une personne dont l'id est {{ person.id }}</h1>
    <table border="1px">
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>les 2</th>
            <th>Email</th>
            <th>Date de naissance</th>
        </tr>
       
            <tr>
                <td>{{ person.getId() }}</td>
                <td>{{ person.firstname }}</td>
                <td>{{ person.lastname }}</td>
                <td>{{ person.fullname }}</td>
                <td>{{ person.email }}</td>
                <td>{{ person.birthdate|date('d/m/Y')}}</td>
            </tr>
     
            
        
    </table>
  
</div>
{% endblock %}

templates/person/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello list person!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>une liste de personne</h1>
    <table border="1px">
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>les 2</th>
            <th>Email</th>
            <th>Date de naissance</th>
        </tr>
        {% for person in persons %}
            <tr>
                <td><a href="{{ path('app_person_detail', {id: person.id}) }}">{{ person.getId() }}</a></td>
                <td>{{ person.firstname }}</td>
                <td>{{ person.lastname }}</td>
                <td>{{ person.fullname }}</td>
                <td>{{ person.email }}</td>
                <td>{{ person.birthdate|date('d/m/Y')}}</td>
            </tr>
        {% endfor %}
            
        
    </table>
  
</div>
{% endblock %}

templates/person/search.html.twig
{# empty Twig template #}
{% extends 'base.html.twig' %}

{% block title %}Recherche{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
   
    <h1>Page de recherche</h1>
    <form action="" method="post">
        <p> <label for="email">email</label>
            <input type="text" id="email" name="email" /></p>
        <p><label for="lastname">nom</label>
            <input type="text" id="lastname" name="lastname" /></p>
        <input type="submit" name="rechercher" value="rechercher" />
    </form>
    {% if person is not null %}
        <table border="1px">
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>les 2</th>
            <th>Email</th>
            <th>Date de naissance</th>
        </tr>
       
            <tr>
                <td>{{ person.getId() }}</td>
                <td>{{ person.firstname }}</td>
                <td>{{ person.lastname }}</td>
                <td>{{ person.fullname }}</td>
                <td>{{ person.email }}</td>
                <td>{{ person.birthdate|date('d/m/Y')}}</td>
            </tr>
        </table>
    {% endif %}   
    {% if persons is not null %}
     <table border="1px">
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>les 2</th>
            <th>Email</th>
            <th>Date de naissance</th>
        </tr>
        {% for oneperson in persons %}
            <tr>
                <td><a href="{{ path('app_person_detail', {id: oneperson.id}) }}">{{ oneperson.getId() }}</a></td>
                <td>{{ oneperson.firstname }}</td>
                <td>{{ oneperson.lastname }}</td>
                <td>{{ oneperson.fullname }}</td>
                <td>{{ oneperson.email }}</td>
                <td>{{ oneperson.birthdate|date('d/m/Y')}}</td>
            </tr>
        {% endfor %}
    {% endif %}
            
        
    </table>
    
  
</div>
{% endblock %}